#ifndef	P_UART_H
#define	P_UART_H

#include "peripherals/base.h"

#define UART_REG_BASE (PBASE + 0x00201000)

#define UART_DR     (UART_REG_BASE+0x00) //UART DATA REGISTER
#define UART_FR     (UART_REG_BASE+0x18) //UART FLAG REGISTER
#define UART_IBRD   (UART_REG_BASE+0x24)
#define UART_FBRD   (UART_REG_BASE+0x28)
#define UART_LCRH   (UART_REG_BASE+0x2C)
#define UART_CR     (UART_REG_BASE+0x30) //UART CONTROL REGISTER
#define UART_RSRECR (UART_REG_BASE+ 0x04)
#define UART_ILPR   (UART_REG_BASE+ 0x20)
#define UART_IFLS   (UART_REG_BASE+ 0x34)
#define UART_IMSC   (UART_REG_BASE+ 0x38)
#define UART_RIS    (UART_REG_BASE+ 0x3C)
#define UART_MIS    (UART_REG_BASE+ 0x40)
#define UART_ICR    (UART_REG_BASE+ 0x44)
#define UART_DMACR  (UART_REG_BASE+ 0x48)
#define UART_ITCR   (UART_REG_BASE+ 0x80)
#define UART_ITIP   (UART_REG_BASE+ 0x84)
#define UART_ITOP   (UART_REG_BASE+ 0x88)
#define UART_TDR    (UART_REG_BASE+ 0x8C)

#endif  /* P_UART_H */
